name: Tests
on: [push]
jobs:
  functional-tests:
    name: Functional tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [windows-latest]
        php-versions: ['7.4']
    steps:
      - name: Prepare database
        run: |
          php bin/console doctrine:database:create
          php bin/console doctrine:schema:update --force
          php bin/console doctrine:fixtures:load -n
      - name: Run functional tests
        run: php vendor/bin/simple-phpunit
      - name: Analyze coding style
        run: php vendor/bin/phpcs