name: Code quality
on: [push, pull_request]
jobs:
  phpcs:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run functional tests
        run: php vendor/bin/phpunit

      - name: Analyze coding style
        run: php vendor/bin/phpcs --standars=PSR12 tests src